Script to download saved objects
openMF/ph-ee-env-template pull request #102
Opened 2023-03-23 13:11 UTC by truthfool

## Description

- Python script to download saved objects of different types for version control

 _(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-03-23 13:11 UTC, truthfool commented
@avikganguly01 @fynmanoj

2023-03-27 06:50 UTC, fynmanoj requested changes

2023-03-27 06:50 UTC, fynmanoj commented on Kibana Visualisations/dashboard/Reporting .ndjson
there is a space in the file name. is that required?

2023-03-27 06:50 UTC, fynmanoj commented on Kibana Visualisations/export-saved-objects.py
> +KIBANA_URL = "https://analytics.sandbox.fynarfin.io/"
make this configurable from a yaml /properties file other than the code

2023-03-27 06:50 UTC, fynmanoj commented on Kibana Visualisations/export-saved-objects.py
> +        "Authorization": "Basic dW5kZWZpbmVkOiRLSUJBTkFQQVNT",
make this configurable and, do not push credentials to github

2023-03-27 06:52 UTC, truthfool commented on Kibana Visualisations/dashboard/Reporting .ndjson
These are getting pulled from our saved objects from kibana. Nothing to do with code.

2023-03-30 07:16 UTC, merged