ClusterRole and clusterRoleBinding #GOV-439
openMF/ph-ee-env-template pull request #151
Opened 2023-05-13 10:27 UTC by somanath21

## Description

* This is a subtask of GOV-439 
* Added cluster role and cluster role binding yaml files.
* Add a link to the design document or include the design bullet points related to this PR here.

 _(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-05-24 15:06 UTC, fynmanoj requested changes

2023-05-24 15:06 UTC, fynmanoj commented on helm/ph-ee-engine/ams-paygops/templates/clusterrole.yaml
> +  name: ph-ee-connector-ams-paygops
add c-role as suffix

2023-05-30 13:03 UTC, somanath21 commented on helm/ph-ee-engine/ams-paygops/templates/clusterrole.yaml
> +  name: ph-ee-connector-ams-paygops
c-role as suffix where?

2023-05-30 13:12 UTC, fynmanoj requested changes
all cluster roles should have the suffix c-role.
Eg: `ph-ee-zeebe-ops-c-role`

2023-05-30 14:28 UTC, fynmanoj approved these changes

2023-05-30 14:28 UTC, merged