#GOV-437 Global parameters to re-use in multiple locations
openMF/ph-ee-env-template pull request #197
Opened 2023-08-01 06:42 UTC by somanath21

(https://mifosforge.jira.com/browse/GOV-437) Description

* Added a Global parameter for the below variables
1. SPRING_PROFILES_ACTIVE
2. ImagePullPolicy
3. LOGGING_LEVEL_ROOT
4. LOGGING_PATTERN_CONSOLE
5. tenants
6. DFSPIDS     

 _(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-08-08 14:02 UTC, fynmanoj requested changes

2023-08-11 12:18 UTC, fynmanoj commented
rebase this PR

2023-08-17 13:39 UTC, fynmanoj approved these changes

2023-08-18 05:44 UTC, fynmanoj commented
The checks should be green to merge it

2023-08-24 10:48 UTC, fynmanoj requested changes
please update the global parameters in ID account mapper

2023-08-24 10:48 UTC, fynmanoj commented
please rebase

2023-08-24 14:48 UTC, somanath21 commented on helm/g2p-sandbox/Chart.yaml
> +  version: 1.8.0-SNAPSHOT
Done

2023-09-01 13:46 UTC, fynmanoj commented
Identity and Voucher services to be included

2023-09-05 10:16 UTC, merged