Updated circle CI to build security chart
openMF/ph-ee-env-template pull request #203
Opened 2023-08-10 07:27 UTC by danishjamal104

## Description

* Describe the changes made and why they were made.
* Add a link to teh design document or include the design bullet points related to this PR here.

 _(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-08-23 13:11 UTC, fynmanoj requested changes

2023-08-23 13:11 UTC, fynmanoj commented on ph-ee-g2psandbox-0.0.0.tgz
remove binaries/ update git ignore

2023-08-23 13:11 UTC, fynmanoj commented on helm/g2p-sandbox-security/README.md
update readme with the steps to install/ setup ingress

2023-08-23 13:27 UTC, danishjamal104 commented on ph-ee-g2psandbox-0.0.0.tgz
done

2023-08-23 13:28 UTC, danishjamal104 commented on helm/g2p-sandbox-security/README.md
done

2023-08-28 11:46 UTC, fynmanoj approved these changes

2023-08-28 11:46 UTC, merged