[PHEE-395] Added environment variables
openMF/ph-ee-env-template pull request #207
Opened 2023-08-16 12:23 UTC by truthfool

## Description

- added env variables for zeebe contactpoint
- added env variables for mock failure percentage

 _(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-08-16 14:11 UTC, truthfool commented
@fynmanoj This pipeline is running from the downstream

2023-08-17 11:53 UTC, fynmanoj requested changes

2023-08-17 11:53 UTC, fynmanoj commented on helm/ph-ee-engine/connector-mock-paymentschema/templates/deployment.yaml
> +              value: "{{ .Values.mockFailure_percentage }}"
other fields also requires this fix

2023-08-17 11:54 UTC, somanath21 reviewed
I think the previous configuration for "value: "{{ .Values.mockpayment.mockFailure_percentage }}"  is correct, as this service do not have its own values.yaml to refer the value from "value: "{{ .Values.mockFailure_percentage }}"

I believe this is because of missing values in ph-ee-engine/g2p-sandbox values.yaml for mockFailure_percentage

2023-08-17 15:24 UTC, somanath21 approved these changes

2023-08-17 16:06 UTC, fynmanoj approved these changes

2023-08-17 16:06 UTC, fynmanoj commented on helm/ph-ee-engine/connector-mock-paymentschema/templates/deployment.yaml
> +              value: "{{ .Values.mockpayment.mockFailure.percentage }}"
remove mockpayment from all values
eg: 

value: "{{ .Values.mockFailure.percentage }}"

2023-08-17 16:08 UTC, fynmanoj approved these changes

2023-08-17 16:19 UTC, merged