Identity Account Mapper
openMF/ph-ee-env-template pull request #213
Opened 2023-08-18 11:18 UTC by apurbraj

## Description

* Deployment file fix for identity account mapper.
* Add a link to teh design document or include the design bullet points related to this PR here.

 _(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-08-18 11:38 UTC, fynmanoj requested changes

2023-08-18 11:38 UTC, fynmanoj commented on helm/g2p-sandbox/requirement.yaml
remove these changes and add them to chart.yaml as dependency.

2023-08-18 11:38 UTC, fynmanoj commented on helm/g2p-sandbox/values.yaml
> +        CREATE DATABASE `IdentityAccountMapper`;
use  lowercase name for database

2023-08-18 11:38 UTC, fynmanoj commented on helm/g2p-sandbox/values.yaml
> +    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/ph-ee-vouchers"
please point to the docker hub images
why the voucher image is used here in account mapper?

2023-08-18 11:38 UTC, fynmanoj commented on helm/g2p-sandbox/values.yaml
> +    hostname: "identity-mapper.sandbox.fynarfin.io"
use mifos.io host name. fynarfin.io shoudl be used in g2p-sandbox-SIT chart

2023-08-18 11:38 UTC, fynmanoj commented on helm/g2p-sandbox/values.yaml
> +        - host: identity-mapper.sandbox.fynarfin.io
use mifos.io host name. fynarfin.io shoudl be used in g2p-sandbox-SIT chart

2023-08-18 11:38 UTC, fynmanoj commented on helm/g2p-sandbox/values.yaml
> +        url: jdbc:mysql:thin://operationsmysql:3306/IdentityAccountMapper
use lowercase db name

2023-08-18 11:38 UTC, fynmanoj commented on helm/identity-account-mapper/values.yaml
> +      - host: identity-mapper.sandbox.fynarfin.io
use mifos.io

2023-08-18 11:38 UTC, fynmanoj commented on helm/identity-account-mapper/values.yaml
> +      url: jdbc:mysql:thin://operationsmysql:3306/IdentityAccountMapper
use lowercase db name

2023-08-18 11:38 UTC, fynmanoj commented on helm/identity-account-mapper/values.yaml
> +      ROOT: DEBUG
by default keep it as info

2023-08-18 11:38 UTC, fynmanoj commented on helm/identity-account-mapper/account-mapper/values.yaml
> +    username: mifos
check how these values are used ( ideally secret should be used)

2023-08-18 11:38 UTC, fynmanoj commented on helm/identity-account-mapper/account-mapper/values.yaml
>  image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/ph-ee-identity-account-mapper"
point it to dockerhub

2023-08-18 11:38 UTC, fynmanoj commented on helm/identity-account-mapper/account-mapper/templates/role.yaml
> +  name: ph-ee-identity-account-mapper-role
no need to create roles for each service, we are using one role for all servcies now

2023-08-18 11:38 UTC, fynmanoj commented on helm/identity-account-mapper/values.yaml
> +  image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/ph-ee-vouchers"
use account mapper image
use the tag inline

2023-08-18 11:38 UTC, fynmanoj commented on helm/identity-account-mapper/values.yaml
> +  imageTag: "latest"
you have removed this from the deployment already

2023-08-18 11:41 UTC, fynmanoj commented
Please attach a ticker or story to each PR

2023-08-24 09:57 UTC, fynmanoj requested changes

2023-08-24 10:39 UTC, apurbraj commented on helm/identity-account-mapper/account-mapper/templates/rolebinding.yaml
> +  name: ph-ee-operator-c-role-binding
changes it to ph-ee-operator-role-binding

2023-08-24 10:42 UTC, fynmanoj approved these changes

2023-08-24 10:43 UTC, merged