testing orb creation
openMF/ph-ee-env-template pull request #295
Opened 2023-11-16 08:14 UTC by logoutdhaval

## Description

* Describe the changes made and why they were made.
* Add a link to teh design document or include the design bullet points related to this PR here.

 _(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-11-20 10:09 UTC, fynmanoj requested changes
review 1

2023-11-20 10:09 UTC, fynmanoj commented on .circleci/docker-image-availability-check-and-upgrade.yml
Please create a documentation on how to use this ORB

Refer: https://circleci.com/developer/orbs/orb/circleci/helm

2023-11-20 11:07 UTC, fynmanoj requested changes

2023-11-20 12:22 UTC, logoutdhaval commented on .circleci/docker-image-availability-check-and-upgrade.yml
> +              JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1)
fixed

2023-11-20 12:23 UTC, logoutdhaval commented on .circleci/docker-image-availability-check-and-upgrade.yml
> +              if docker_tag_exists openmf/community-app ${JIRA_STORY}; then
I can not use any loops here as env var are different for each service.

2023-11-27 07:29 UTC, logoutdhaval commented on .circleci/docker-image-availability-check-and-upgrade.yml
Here is the doc for creating and using an orb in circleci.

https://docs.google.com/document/d/1u-nhZVWaFqNXucdWn3RD50ObXdi6TEAwU-4lgYLyMAI/edit

2023-11-27 10:14 UTC, fynmanoj approved these changes

2023-11-27 10:14 UTC, merged