[PHEE-528] helm deploy and helm test in minikube
openMF/ph-ee-env-template pull request #342
Opened 2024-01-08 11:16 UTC by somanath21

## Description

* PR title should have jira ticket enclosed in `[]`.<br>
Format: ``` [jira_ticket] description```<br>
ex: [phee-123] PR title.
* Add a link to the Jira ticket.
* Describe the changes made and why they were made.

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!
- [ ] Followed the PR title naming convention mentioned above.

- [ ] Design related bullet points or design document link related to this PR added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Created/updated unit or integration tests for verifying the changes made.

- [ ] Added required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2024-01-17 13:47 UTC, fynmanoj requested changes

2024-01-17 13:47 UTC, fynmanoj commented on .circleci/config.yml
> +            sudo apt-get update
please move all the installations to the start of the script. we should plan to create a docker file with all these installations to make the process faster

2024-01-17 13:47 UTC, fynmanoj commented on .circleci/config.yml
> +            helm test my-ph-ee-g2psandbox -n paymenthub --timeout 5m
increase this time out, our tests might take more than 5m

2024-01-17 13:47 UTC, fynmanoj commented on .circleci/config.yml
> +            sh orchestration/deployBpmn.sh || echo 'deploy Bpmn done'
this is already been added as a job in the chart. do we need to repeat?

2024-01-17 13:47 UTC, fynmanoj commented on .circleci/config.yml
> +            cd elastic/helm-charts/elasticsearch/examples/security/
these steps are already part of the job, can be removed

2024-02-15 06:40 UTC, fynmanoj commented
@somanath21 , Is this PR up to date for merging? , Update to get this merged or close this PR, 
it is been  open for a long time

2024-04-01 11:33 UTC, somanath21 commented
Ephemeral story is completed

2024-04-01 11:33 UTC, closed without merging