Added environment variables and Paybill APIs
openMF/ph-ee-env-template pull request #37
Opened 2022-10-18 10:15 UTC by truthfool

- Added Paybill apis in payment hub collection
- Added necessary environment variables in SIT environment json
Note : Paygops does not have ingress defined so kept it as localhost.
@fynmanoj

2022-10-18 13:59 UTC, fynmanoj requested changes

2022-10-20 12:35 UTC, truthfool commented on PostmanCollections/Payment Hub.json
> +			"name": "Paybill APIs",
Ok got it.

2022-10-20 12:36 UTC, truthfool commented on PostmanCollections/Environment/SIT.json
> +			"value": "http://0.0.0.0:5002",
I will create ingress for paygops and roster both and add it.

2022-10-20 12:36 UTC, truthfool commented on PostmanCollections/Environment/SIT.json
>  	"name": "SIT",
I will keep the id as previous such that the integration tests will run.

2022-11-09 18:28 UTC, fynmanoj commented on PostmanCollections/Environment/SIT.json
>  	"name": "SIT",
integration test is not run using the ID, It is run based on the name in one environment variable

2022-12-08 11:11 UTC, closed without merging