[PHEE-569] Create tenants
openMF/ph-ee-env-template pull request #374
Opened 2024-02-09 05:17 UTC by somanath21

(https://fynarfin.atlassian.net/browse/PHEE-569)
## Description

* PR title should have jira ticket enclosed in `[]`.<br>
Format: ``` [jira_ticket] description```<br>
ex: [phee-123] PR title.
* Add a link to the Jira ticket.
* Describe the changes made and why they were made.

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!
- [ ] Followed the PR title naming convention mentioned above.

- [ ] Design related bullet points or design document link related to this PR added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Created/updated unit or integration tests for verifying the changes made.

- [ ] Added required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2024-02-09 09:13 UTC, fynmanoj requested changes

2024-02-09 09:13 UTC, fynmanoj commented on helm/g2p-sandbox/values.yaml
> +        GRANT ALL PRIVILEGES ON `Pluto`.* TO 'mifos';
keep database names in lowercase

2024-02-09 11:12 UTC, somanath21 commented on helm/g2p-sandbox/values.yaml
> +        GRANT ALL PRIVILEGES ON `Pluto`.* TO 'mifos';
done

2024-02-13 16:18 UTC, fynmanoj approved these changes

2024-02-13 16:18 UTC, merged