Redis Configuration
openMF/ph-ee-env-template pull request #96
Opened 2023-03-16 14:25 UTC by truthfool

## Description

- Redis deployment and service

 _(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-03-16 14:25 UTC, truthfool commented
@fynmanoj @avikganguly01 @somanath21

2023-03-16 14:59 UTC, fynmanoj requested changes
Clarification Requested

2023-03-16 14:59 UTC, fynmanoj commented on helm/ph-ee-engine/templates/dev-redis.yaml
> +{{- if .Values.redis.enabled -}}
Do we need to add the redis chart like this? Do t we have any ready made chart available from online providers like bitnami?

2023-03-21 06:03 UTC, fynmanoj commented
closing this PR as we need to add the redis as a depoendency

2023-03-21 06:03 UTC, closed without merging