Redis and Business Short Code Configuration
openMF/ph-ee-env-template pull request #98
Opened 2023-03-21 09:41 UTC by truthfool

## Description

- Redis Configuration
- Business Short Code Configuration

 _(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-03-21 09:41 UTC, truthfool commented
@fynmanoj @avikganguly01

2023-04-06 07:38 UTC, fynmanoj requested changes
I could see a master/slave ( 2 nodes) came alive for redis in SIT, can you change this to single Node ? we need Bare minimus setup as default

2023-04-06 15:01 UTC, fynmanoj commented on helm/ph-ee-engine/values.yaml
> +    replicaCount: 1
we don't need two nodes for the bare minimum setup. use disable options to disable one node

2023-04-13 12:49 UTC, truthfool commented on helm/ph-ee-engine/values.yaml
> +    replicaCount: 1
Done

2023-04-20 12:54 UTC, fynmanoj commented on helm/ph-ee-engine/values.yaml
> +    replicaCount: 1
is it tested?

2023-04-21 05:08 UTC, merged